# Training and Research Compliance

----------

## Essential training  

All lab members complete and keep track of the following training:

* Responsible Conduct in Research Training
  + Please visit the [RCR website](https://cws.auburn.edu/OVPR/pm/compliance/rcr/home). Click on “Follow these steps to access the new course.”  Login to CITI and select Auburn University (you must do this for your training to be properly credited to you at Auburn).
  
* Lab safety training (Auburn University) is available through [BioRaft](https://cws.auburn.edu/rms/pm/OnlineTraining).

* Cybersecurity training
  + To access the training, log into AU Access and select the Employee Services tab. Next, click the icon. You will be directed to the training videos library that contains the required modules. To view the videos, select a module and click the icon. The videos may be viewed in any order. Typically, within 24 hours after you have completed the modules, you will receive an email confirmation from <noreply@auburn.edu> along with a certification of completion.

* Driver’s Safety training
  + Register and follow the directions on [this page](https://cws.auburn.edu/shared/files?id=227&filename=Driver%20Safety%20Training%20PKI.pdf).

* We are regularly exposed to venomous insects (fire ants, bees, wasps) in the field. Likewise, food-based allergies are common and not always known or disclosed. To be prepared, graduate students and undergraduates are expected to complete and have verification of Anaphylaxis Training effective immediately for existing students or before they begin fieldwork. The ADPH Anaphylaxis Training through BIORAFT is our best option. Sorry, this is an older, low-quality 16-minute video, but it is the only source from which training can be verified. A short quiz following the video for you to complete confirms the knowledge gained from this training. This will also show in your Bioraft profile. The epi-pen website has modern graphics and videos but does not provide a way to verify that training was completed. You can use this to support your knowledge gain is needed.

* We use various cutting tools (e.g., axe, hatchet, saw, knife) in termite research. The most important thing is mentioned in this [video](https://originaloutdoors.co.uk/article/axe-safety-basics-simple-rules-for-using-axe-safely-bushcraft-woodcraft/). Please have a look at this. Make sure your body is not in the way to swing. Also, wear a glove.

Once completed, please save the completion records as PDF.


----------

## Scientific Integrity

### Authorship
Authorship of papers and presentations is an important and sensitive topic in academia.
There is little consensus on the criteria for authorship on collaborative projects, most guidelines suggest authorship be given to those who made *significant intellectual contribution* to the study.
So, what is the significant intellectual contribution? It could be contributions to the conception or design of the work and acquisition, analysis, or interpretation of the data. Thus, authorship is clear for those who designed the experiments, performed behavioral observations, analyzed the videos, and wrote the paper. However, there are many unclear situations; I will provide examples here.  
We will keep updating these examples based on our experiences.  
  
1. *I designed the research and performed the experiments to obtain data. I paid you as an assistant and instructed you to use tracking software to obtain trajectories for movement analysis. Then, I analyzed these data and wrote a paper.*

* In this case, I believe that you will not be an author because just using tracking software to obtain trajectories does not involve much intellectual input. Thus, to include you as the author, I will ask for more intellectual involvement (e.g., doing more analysis beyond just using tracking software, watching videos to obtain insights, and co-writing a paper). At the beginning (ideally), we will discuss how to treat authorship.
    
2. *We received a rare species (or samples) for behavioral observation from a collaborator. This sample is hard to collect but essential to answer some questions about the behavioral study, and we cannot obtain it without this collaborator's knowledge.*

* This is the most challenging and controversial one. I believe this could be an intellectual contribution. This is because sampling insects in the field often requires intellectual work. We may not have a way to collect it due to the lack of intellectual ability. However, we should ask this collaborator if (s)he is happy to be involved as a co-author because some people regard providing materials as not being included in intellectual contributions. Furthermore, I think it is better to ask to provide more than samples, e.g., feedback on the research plan, basic life history information of the samples while collection, and editing the draft to improve it. This practice can be applied to many situations.  
  
3. *You worked on a side project that is outside of my expertise. You performed the research outside your working hours, and I have not contributed training or funding for that work.*

* I do not expect to be an author. However, I am still happy to give you feedback on the work (as an acknowledgment).

4. *Similar to above. You worked on a side project that relates to my expertise. You performed the research outside of your working hours, but you used the shared or common resources in the lab, which are from my funding.*

* I do not expect the authorship as I think providing lab resources is not counted as authorship (we should know that somebody does). However, I may feel sad as this project is within my expertise, and I might want to contribute by offering some insights. Please communicate well. You may be able to think about my role as a contribution to enhance the process or even make this a lab project to work on during working hours. Obtaining such ability is actually important, especially when you start collaborations with various people in the future.
  
As for the main project led by Mizumoto lab, the trainees who are driving the project are expected to be the first author, and NM is expected to be the senior (i.e., last) author. Other trainees who help over the course of the project may also be authors, depending on their contributions. As it is sometimes hard to predict exactly where a project will end up (data collection, cleaning, and analysis in developmental labs can take a long time), the positioning of non-primary and non-senior authors will be decided when the paper is drafted. If a trainee takes on a project but subsequently hands it off to another person, they will most likely be handing over first authorship to that person too. We may use a co-first author when appropriate. All of these issues have to be discussed openly.

----------

### Data management

**A story**  
I know the story of a silly doctoral student named Nobuaki Mizumoto at Kyoto University. In 2017, the last year of his PhD, he had several ongoing projects. Two projects require watching videos to record termite mating behavior and counting numbers. After many hours of watching with hard work, he finished obtaining the data. However, he put all the data of these two projects in a single HDD without backup. One summer day, he came to the lab early in the morning and realized that a weird clicking sound had come from his HDD. Yes, the HDD died. He was upset, and his heart was pierced with a pang of regret for the next three weeks. Fortunately, he could make it. He found a service called Seagate Data Recovery. He paid about $700 and sent his HDD from Japan to the US. They succeeded in salvaging the data. And he decided to put all the non-video data into Dropbox and make multiple backups for videos. You can see the acknowledgment of this [paper](https://doi.org/10.1101/2024.02.01.578198): _"We also appreciate Seagate Recovery Services (https://www.seagate.com/products/rescue-data-recovery/) for recovering our data after an unexpected loss and emphasizing the importance of backups."_  Fin.
  
**Data backup**  
Long story short. **Make a backup for your data, codes, and drafts.**
In Mizumoto Lab, all the data, code, and drafts must be stored in either OneDrive or Box Drive (see [Data management practices]). Auburn University provides the [access](https://auburn.box.com). All these data for every single project should be stored in a single folder (also managed using GitHub), which has a minimum structure of  

* root
  + README
  + analysis
    + .Rproj file
    + code
    + data_raw - folder containing raw data
    + data_fmt - folder containing data converted from raw data
    + output - folder containing outputs
  + draft

Furthermore, all the video files are stored in the lab HDDs. All HDDs are tracked in this [spreadseat](https://docs.google.com/spreadsheets/d/1fEPiFSkb0jT4uTSYt_Y7oYhSlYMmxZmwHc3rapNOAlc/edit?gid=0#gid=0). We currently have 320TB storage and will be expanded. Ask NM for the access.

----------

### Reproducible Research
 
The Mizumoto is committed to performing reproducible research. Reproducible research means that somebody with your raw data and code can reproduce your results exactly. If they can’t, it suggests that something is wrong or that you did not properly document the data collection, cleaning, or analysis process. Neither of these options is good. Therefore, we ensure that all aspects of the data collection, cleaning, and analysis are extremely well documented.
 
For results to be reproducible, you must be organized and document everything. Take notes on your study design (e.g., size of the arena, number of termites, colonies, how they are treated, etc.), experimental conditions (e.g., temperature, illumination, time, date, etc.), and what you did. When you write a code, leave comments so that other people (including yourself in the future) can understand the code. If something goes wrong or something unusual happens, document that too. Take photos/videos of what you saw.

----------

### Old Projects
 
If a trainee drives a project and collects data but does not complete the project (= write a paper) within a reasonable time frame (should depend on the projects) after the data collection, NM may discuss with the trainee handing the project off to someone who can complete it to expedite publication. If a trainee no longer wishes to work on a project at any time and/or no longer wants to be an author, NM will re-assign the project to another individual. This policy is here to prevent data from remaining unpublished. Remember we killed our insects for our research to get that data.

----------
