# General Policies

----------

## Pay rates
  
-------

### Graduate students
All graduate students in the Department of Entomology & Plant Pathology are paid as RA (Research assistantship). GRA represent an appointment of 0.33 FTEs. No graduate student can work more than 0.5 FTE and they typically are not less than 0.25 FTE. This means a student is responsible for working at least 13.2 hours weekly on research outside of their thesis/dissertation on work that contributes directly to the performance of research in the lab. This includes assisting your lab mates with their work. These hours are not monitored currently because we have a culture of collegiality where students willingly assist one another as needed with field or lab projects. Only when a student is clearly not contributing to the work of the lab will these hours be monitored or enforced. Students are responsible for paying all the various university and health fees.   

Base pay rates for students on GRA fellowships are set departmentally.
* MS degree: $23,000 + 3.80% Fringe benefit
* PhD degree: $25,000 + 3.80% Fringe benefit

#### Productivity incentives
Ultimately, the job of researchers is writing. Therefore, graduate students are encouraged to write their work as they progress through their degree program.

* Graduate students must co-author (first or second author position) a manuscript with Dr. Mizumoto worthy of submission to a research journal to be eligible for incentives.

* $500 per year added to stipend. Student is 1st or corresponding author; Held as a co-author.

* Another additional student co-authors: $250 one-time award in student account

· Most Entomology journals have an impact factor of 4 or less. Research in journals with IF greater than these norms are considered exceptional. Any graduate student that publishes research in a journal with an Impact Factor >5 will receive $500 per paper deposited in their student account once accepted. This is in addition to the incentives already listed for publications.

These following incentives for developing skills in grant writing. All proposals must have D.Held as a co-author to be eligible for incentives. An application package typically includes formatted (according to the RFA/RFP) sections, budget narrative and budget. The Narrative also outlined in the RFP is the single largest component of each package. We must have the package complete 2 wk in advance of the deadline published in the RFA. Intention to submit should be done no less than 30 d before the grant deadline.

<!-- Most student pay is tied to grant funded projects. The pay rates written into those projects are finite and not subject to within project increases. Any disparity between grant funded assistantships and the departmental minimums will be addressed if soft funds are available. Some students may also be partially supported with a Departmental GRA fellowship. These fellowships contribute a maximum of $16,000 annually to the base pay rates for GRA fellowships listed below. Base pay rates for students on GRA fellowships are set departmentally through a vote of the faculty. Students are responsible for paying all the various university and health fees. The following annual pay rates (approved by the dept faculty in 2017) vary by degree program.-->

### Undergraduates
Undergraduate students pay rates usually begin at $10 per hour. Undergraduate student support is only possible if funded in the grant that supports a project. Therefore, there may be disparity in how undergraduate student labor is assigned to different projects. If no funding is in the project for undergraduate labor, none should be expected.

GTA fellowships of $1000 per semester are available occasionally through the department. These funds are provided to a student account for the additional work required for a GTA. These GTA fellowships must be approved by the department Chair.



· State or commodity grants:

o Write narrative and manage funded project, budget, and annual reports

§ $500 per year added to stipend when submitted and accepted by sponsor.

§ Another $500 per year added to stipend when project is funded or funds disbursed.

§ Must see project through to completion with required report or funds rescinded.

§ Max of 3 per year.

§ Examples; IR-4, Commodity board grants, Chemical company grants/awards, contracts, Alabama Specialty Crop Block grants

· Federal grant:

o Co-author a proposal with D. Held, develop and manage the budget, write annual reports

o $1500 per year added to stipend when a proposal is submitted by Research office and accepted by sponsor.

o Salary up to $30,000 per year in budget if accepted, and 2% per year pay rate increase in budget.

o If IDC is 42% then another $1500 annually from IDC each year the grant funded. If NSF, then $2000 annually from IDC to stipend.

o Must completed annual reports or funds rescinded.

· Incentive for authoring a AAES proposal. Students that draft and assemble an AAES grant proposal package will receive a $500 payment in their student account upon acceptance of the submission. The grant must have a budget for the Held lab and must have D Held as lead or co-PI. The AAES rules related to PI eligibility apply but this incentive has no other limits on how often it can be applied during a student’s time in the lab.


## Lab meetings and seminars

----------

1. **Daily journal club**
  + Mizumoto lab has a daily journal club (TBD, 11:30am-12:00pm?). No preparation will be required other than downloading pdf or printing it. We will read one paper together within 30 min. If you find a paper you want to read, just add it to the list (___link___).
  
2. Department seminar
  + Department of Entomology & Plant Pathology has a department seminar during semesters, and you are expected to attend it. Ask a question even if it is very different from our field (mostly they are!). Thinking about what to ask for a question is a most effective way to attend seminars.

3. Lab meeting
  + I am thinking of a biweekly lab meeting to present the progress. Discuss this later.

4. Shared Lab Meeting
  + We have shared lab meeting between Clint Lab (Entomology), Mizumoto Lab (Entomology), and Smith Lab (Biology) on collective behavior in social insects. This is a monthly meeting on the first week of Friday.

5. Annual evaluation meeting
  + All trainees will have one-to-one annual evaluation with PI (NM), where PI provides an evaluation with a trainee, and trainee provides an evaluation with PI. I will provide a one-page sheet for the evaluation.

## Noise Policy

----------

Sharing a lab space is hard as we all need a place to focus and work quietly. However, I hope that we like one another and want to chat and have fun too. No matter who is in the lab when you are in, try to respect these general guidelines:

- Always speak in a hushed voice. Remember there are other labs near us as well and we want to be respectful of all our colleagues.
- If someone is wearing headphones and has their ‘do not disturb’ sign up, do not disturb them.
- When speaking with participants on the phone, use one of the testing rooms and close the door.
- If the door to the testing rooms are closed, be extra quiet. It likely means that we have a participant in the lab, or we are speaking to a participant on the phone.

When the lab gets larger, or even now, you (graduate students, postdocs, undergrads, lab managers, research assistants, undergraduates) might want to organize lunchtime events. These could be where you leave the lab and sit outside as a group for lunch (a very healthy thing to do!) and do all your catching up with one another there, or where you discuss specific topics over lunch – e.g., I have seen some colleagues have fun with ‘lunch hacks’ or ‘coding circles’ where you work over coding problems together in your lunch break (allowing everyone to save up their questions for that time of the day, rather than disturb others while they are trying to work). Obviously, I will leave that up to you all, but these are some of the ways that allow for fun lab socialization without disturbing work hours.

----------
 
## PI Office Hours

In addition to weekly meetings (see below), Bridget will host open office hours once every two months for volunteer RAs, undergraduate students, research staff, postdocs, and grad students to schedule 1-on-1 meetings with her. To do this, she will share her calendar so that lab members can book a slot. You may discuss anything you like in these meetings - for instance, professional development, an ongoing project, or anything else. 

----------

## Meetings

### Weekly Lab Meetings
 
It is my expectation that all lab members are aware of what each other are working on. In knowing (and taking interest in what your lab mates are working on) it will make it feel like a lab community, rather than a bunch of people collaborating one-on-one with the PI. One of the forums where we can learn about each other’s work is in weekly lab meetings. These lab meetings will be approximately 1 hour and may involve a group project troubleshoot (~15-30 minutes), and a goal blitz for the week or month ahead (<5 minutes per person) at the start of the meeting. For the remaining time in the lab meeting, we will have different approaches depending on the amount of data and the stage of current projects. To begin with, while the Mind, Brain Body study is getting setup, one option (Thematic Learning option) is to define an area of interest that the lab wants to learn more about at the start of the term, and then have lab members present on articles on their choosing that focus on the agreed-upon themes in a journal club style. When the lab has some data to work on, we might begin to transition to a mix of Thematic Learning and Works in Progress. Works in Progress simply means that students take time to present their analyses or projects.
 
The group project troubleshoot will involve us working through problems that relate to the large group project (at this stage, the large group project is the Mind, Brain, Body project, funded through Bridget’s R00). As all lab members contribute to data collection for that project, we will talk about procedural issues like recruitment, planning the next wave of data collection etc. Troubleshooting for smaller individual projects will occur during one-and-one meetings with the PI (see below) and during the WIP session.
 
Goal blitz will involve every lab member going around and giving a very brief update of what they achieved during the week, and what their goals are for the coming week. This should be prepared ahead of time, and succinct! This will help everyone know what stage we are all at with our projects, and can also help with planning procedural issues – e.g., if many people are planning to be debugging code in the coming week, it might make sense to set up a code lunch so that you can help one another out.
 
Thematic Learning: The core lab member will identify an area of research that is relevant to the lab at the moment, or to their present work. For example, if we are discussing different memory assessments to add to the protocol for Mind, Brain, Body, the lab member could make a syllabus on the theme of ‘measurement of memory across development’. They would then identify several papers in the area to put into a reading list (i.e., make a bibliography) and then assign some of the more pertinent papers to be discussed during Thematic Learning. Each student in the lab would then take turns leading the thematic learning component of the lab meeting on one of the assigned papers. Old syllabi will be available for new students to read, so that they can get up to date with the things we have been working on in the lab. This is a great way to get experience developing syllabi, teaching, and contributing to the knowledge base in the lab.  
 
Works-in-Progress (WIP) will be assigned to one lab member each week during months where we are not doing Thematic Learning. This is an opportunity to present some data, or a task, or an idea that you are working on. Works-in-Progress are just that, in progress. This means that they should not be perfect presentations, but instead, should be a ‘warts and all’ look at what is going on with the data, analysis, code etc. The idea is to work as a group to constructively provide feedback and help one another move forward.
 
Occasionally, we may have joint lab meetings with other faculty in the department – these may be combined with our weekly lab meeting or an additional meeting. We will also use lab meetings (or ad-hoc scheduled meetings) to prepare for conference presentations and give people feedback on job talks or other external presentations. Lab meeting agendas and notes will be kept in the #lab-meetings channel on Slack.
 
### Individual Meetings
 
At the beginning of each term, we will set a schedule for weekly meetings. Each full-time lab member (RAs, graduate students, post-docs) will have a half-hour slot set aside to meet with Bridget. If scheduling conflicts arise (e.g., because of travel), we can try to reschedule for another day that week. If there is nothing to discuss, feel free to cancel the meeting or just drop by for a brief chat. If you need to speak for longer – please give advanced notice.
 
For full-time lab members, you should come to individual meetings prepared to talk about your career goals, your training goals, procedural aspects of your project, and your data. When we talk about your data, I suggest you bring along an R-Markdown file, or Keynote/PowerPoint that includes your raw data (e.g., histograms, scatter plots etc.) as well as any analyses that have been done, and figures produced from those analyses. This will help us to make the best use of our time and will save us digging around for data while we are meeting.
 
Post-docs, graduate students, and lab managers should meet with their undergraduate mentee/s on a regular basis.

----------

## Deadlines

One way of maintaining sanity in the academic work is to be as organized as possible. This is essential because disorganization doesn’t just hurt you, it hurts your collaborators and people whose help you need. When it comes to deadlines, tell your collaborators as soon as you know when a deadline is, make them a calendar reminder, and make sure you give them a friendly follow-up reminder about a week before the deadline.
 
For tasks with a hard deadline, but that don’t require a lot of time (e.g., reading/commenting on conference abstracts, filling out paperwork, etc.), please give Bridget at least a 7-day window. For tasks that require a moderate degree of work (e.g., a letter of recommendation), please give Bridget about a 3-week window (if possible). If you want feedback on research and teaching statements, or other work that requires multiple back-and-forth interactions between you and Bridget before a hard deadline, give her as much time as you can; a month or more.
 
For manuscript submissions and revisions (i.e., which either have no deadline at all or only a weak deadline), send drafts to Bridget as soon as you have them. She will get to them as soon as she gets a chance. Feel free to follow-up if you haven’t heard anything in a few weeks.

----------

## Presentations

Learning to present your research is important. Very few people will read your papers carefully (sad, but true) but you can reach a lot of people at conference talks and posters. Also, if you plan on staying in academia, getting a post-doc position and getting a faculty position both significantly depend on your ability to present your data. Even if you want to leave academia, presentations are likely to be an important part of your job. Additionally, every time you present your work, you are representing not just yourself but the entire lab.

##Credit and Authorship Marek edited this page on Nov 29, 2022 · 9 revisions
The touchy subject of authorship
Authorship on papers, presentations, and reports is an explicit way of assigning credit for scholarly work. As a general and rather vague rule, most authorship guidelines suggest authorship be given to those who made substantial direct intellectual contributions. Huh? I think it makes sense to interpret this generously and elaborate with examples:

Example 1. You are an RA and I paid you for a semester to generate sequence data in the lab. I believe you deserve authorship on the first paper that uses this data. This is because molecular laboratory work is intellectually engaging and often requires significant problem-solving skills.

Example 2. One week I asked you to organize a freezer overflowing with samples from multiple projects in the lab. This took hours of tedious work. I do not believe this entitles you to authorship on all those projects because the activity did not involve much intellectual input. This kind of help belongs in the Acknowledgments section.

Example 3. I have trained you in how to do molecular work for your project, provided feedback on your small travel grant, and paid for sequencing of your samples. I helped you conceptualize your dissertation work and expect you to also solicit feedback from me on your presentations and manuscripts resulting from your work. You should include me as an author.

Example 4. You have worked on a side project that is outside of my realm of expertise. You performed the research outside of your RA hours and I have not contributed training or funding for that work. I am still happy to give you feedback on the products resulting from this but I do not expect to be an author.